# Generated by Django 4.2 on 2023-08-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221229_2212'),
        ('blog', '0003_auto_20221229_2218'),
    ]

    operations = [
    ]
